### ISSUE TITLE
Name clashing

### ISSUE THREAD

**Issue by crazyirish** [jadeclan/Assign1#11]
I think it would be beneficial to have 3 separate namespaces:

Application\API
Application\Dashboard
Application\Dashboard2

Then we wouldn't have to name our controllers Card1Dash2 and Card1B which is confusing.

**Comment by jadeclan** [comment]
Created namespaces for
Application\API\Controllers and
Application\API\Models
All goofy file names have been eliminated by using namespaces.
Did not put the continents, visits, countries, device types, device brands, or referrers into the Application\API\Controllers namespace.  I did it for browsers before I realized it wasn't necessary.
